# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo Browser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Photo Browser
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.8'

end
